# Project type
type = "androidLibrary"

enableMetro = true
enableCompose = true

# Libraries to be used (maven address or version catalog name)
[dependencies]
implementation = [
    { type = "platform", module = { type = "library", name = "androidx.compose.bom" } },
    { type = "library", name = "androidx.compose.foundation" },
    { type = "library", name = "androidx.compose.material3" },
    { type = "library", name = "androidx.compose.ui" },
    { type = "library", name = "androidx.compose.ui.text" },
    { type = "library", name = "androidx.compose.viewmodel" },
    { type = "library", name = "metrox.viewmodel.compose" },
]

api = [
    { type = "library", name = "androidx.lifecycle.viewmodel" },
    { type = "library", name = "androidx.compose.runtime" },
    { type = "library", name = "androidx.navigation3.runtime.android" },
    { type = "library", name = "androidx.foundation.layout" },
    { type = "library", name = "metrox.viewmodel" },

    { type = "project", name = ":home:api" }
]

debugImplementation = [
    { type = "library", name = "androidx.compose.ui.tooling" },
]
