# Project type
type = "javaLibrary"

# Libraries to be used (maven address or version catalog name)
[dependencies]

implementation = [
    { type = "library", name = "kotlinx.serialization.json" },
    { type = "library", name = "kotlinx.serialization" },
]

api = [
    { type = "library", name = "metro.runtime" },
    { type = "library", name = "retrofit" },
]
