steps:
  - label: "Run Unit Tests"
    agents:
      queue: "android-queue"
    command: ./gradlew test

  - label: "Run Build-Logic Tests"
    agents:
      queue: "android-queue"
    command: ./gradlew -p build-logic test

  - label: "Build StarryNight Release"
    agents:
      queue: "android-queue"
    command: |
      buildkite-agent secret get STARRYNIGHT_JKS | base64 --decode > starrynight-release.jks
      ./gradlew :starrynight:app:assembleRelease
    secrets:
      STARRYNIGHT_JKS_PASSWORD: STARRYNIGHT_KEYSTORE_PASSWORD
      STARRYNIGHT_KEY_ALIAS: STARRYNIGHT_ANDROID_KEYSTORE_ALIAS
      STARRYNIGHT_KEY_PASSWORD: STARRYNIGHT_ALIAS_PASSWORD
