steps:
  - label: "Run Unit Tests"
    command: ./gradlew test

  - label: "Run Build-Logic Tests"
    command: ./gradlew -p build-logic test

  - label: "Build StarryNight Release"
    command: ./gradlew :starrynight:app:assembleRelease
