# Project type
type = "androidLibrary"

enableMetro = true
enableCompose = true

# Libraries to be used (maven address or version catalog name)
[dependencies]
implementation = [
    { type = "platform", module = { type = "library", name = "androidx.compose.bom" } },
    { type = "library", name = "androidx.browser" },
    { type = "library", name = "androidx.compose.foundation" },
    { type = "library", name = "androidx.compose.viewmodel" },
    { type = "library", name = "androidx.compose.ui" },
    { type = "library", name = "androidx.compose.ui.graphics" },
    { type = "library", name = "androidx.compose.ui.text" },
    { type = "library", name = "androidx.compose.ui.unit" },
    { type = "library", name = "androidx.core" },
    { type = "library", name = "androidx.lifecycle.common" },
    { type = "library", name = "androidx.lifecycle.runtime.compose" },
    { type = "library", name = "kotlinx.coroutines.core" },
    { type = "library", name = "androidx.compose.ui.tooling.preview" },
    { type = "library", name = "metrox.viewmodel.compose" },

    { type = "project", name = ":home:api" },
    { type = "project", name = ":navigation:api" },
    { type = "project", name = ":starrynight:theme" },
    { type = "project", name = ":utils:core:api" },
]

api = [
    { type = "platform", module = { type = "library", name = "androidx.compose.bom" } },
    { type = "library", name = "androidx.compose.runtime" },
    { type = "library", name = "androidx.foundation.layout" },
    { type = "library", name = "androidx.lifecycle.viewmodel" },
    { type = "library", name = "metrox.viewmodel" },
    { type = "library", name = "androidx.compose.material3" },
    { type = "library", name = "androidx.navigation3.runtime.android" },

    { type = "project", name = ":auth:api" },
    { type = "project", name = ":login:api" },
]

debugImplementation = [
    { type = "library", name = "androidx.compose.ui.tooling" },
]
