# Project type
type = "androidLibrary"

enableMetro = true
enableCompose = true

# Libraries to be used (maven address or version catalog name)
[dependencies]
implementation = [
    { type = "platform", module = { type = "library", name = "androidx.compose.bom" } },
    { type = "library", name = "androidx.browser" },
    { type = "library", name = "androidx.compose.material3" },
    { type = "library", name = "androidx.compose.viewmodel" },
    { type = "library", name = "androidx.navigation3.runtime" },
    { type = "library", name = "kotlinx.coroutines.core" },
    { type = "library", name = "androidx.compose.ui.tooling.preview" },
    { type = "library", name = "metrox.viewmodel.compose" },

    { type = "project", name = ":auth:api" },
    { type = "project", name = ":home:api" },
    { type = "project", name = ":login:api" },
    { type = "project", name = ":navigation:api" },
    { type = "project", name = ":theme" },
]

debugImplementation = [
    { type = "library", name = "androidx.compose.ui.tooling" },
]
