# Project type
type = "androidLibrary"

enableMetro = true

# Libraries to be used (maven address or version catalog name)
[dependencies]

implementation = [
    { type = "project", name = ":atproto" },
    { type = "project", name = ":utils:core:api" },
    { type = "project", name = ":network:core:api" },
    { type = "library", name = "kotlinx.coroutines.core" },
    { type = "library", name = "kotlinx.serialization" },
    { type = "library", name = "kotlinx.serialization.json" },
    { type = "platform", module = { type = "library", name = "okhttp.bom" } },
    { type = "library", name = "okhttp" },
    { type = "library", name = "okhttp.coroutines" },
    { type = "library", name = "retrofit" },
    { type = "library", name = "retrofit.kotlin.serialization" },
]
