# Project type
type = "androidLibrary"

# Libraries to be used (maven address or version catalog name)
[dependencies]

implementation = [
    { type = "project", name = ":atproto" },
    { type = "project", name = ":network:core:api" },
    { type = "library", name = "kotlinx.serialization" },
    { type = "library", name = "kotlinx.serialization.json" },
    { type = "library", name = "retrofit" },
    { type = "library", name = "retrofit.kotlin.serialization" },
]
