# Project type
type = "androidApplication"

applicationId = "com.frybits.starrynight.android"

targetSdk = 36
#previewTargetSdk

enableCompose = true
enableMetro = true

# Libraries to be used (maven address or version catalog name)
[dependencies]

# Used to add libraries into the "implementation" configuration
implementation = [
    { type = "platform", module = { type = "library", name = "androidx.compose.bom" } },
    { type = "library", name = "androidx.activity.compose" },
    { type = "library", name = "androidx.core" },
    { type = "library", name = "google.material" },
    { type = "library", name = "metrox.android" },
    { type = "library", name = "kotlinx.coroutines.android" },

    # Api modules
    { type = "project", name = ":atproto:api" },
    { type = "project", name = ":auth:api" },
    { type = "project", name = ":network:api" },
    { type = "project", name = ":persistence:api" },
    { type = "project", name = ":utils:core:api" },

    # Data modules
    { type = "project", name = ":atproto:data" },

    # Impl modules
    { type = "project", name = ":atproto:impl" },
    { type = "project", name = ":auth:impl" },
    { type = "project", name = ":network:impl" },
    { type = "project", name = ":persistence:impl" },
    { type = "project", name = ":utils:core:impl" },
]

# Used to add libraries into the "api" configuration
#api = [
    # Example types to add: "project", "library", "platform"
    # { type = "project", name = ":foobar" },
    # { type = "library", name = "androidx.core" }, # Name here should match version catalog dot naming convention
    # { type = "platform", module = { type = "library", name = "kotlinx.coroutines.bom" } },
#]
