/*
 * Starry Nights - A BlueSky Android Client
 * Copyright (C) 2026 Pablo Baxter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.frybits.gradle.android.wrappers

import com.android.build.api.dsl.CompileOptions
import com.android.build.api.dsl.CompileSdkSpec
import com.android.build.api.dsl.DefaultConfig

/**
 * This class wraps the [com.android.build.api.dsl.CommonExtension] class. The purpose for this is due to
 * AGP changing the generics of this class in AGP 8, and a binary breaking change in AGP 9.
 *
 * The only functions, variables, properties available for [com.android.build.api.dsl.CommonExtension] are the ones provided here.
 */
public interface CommonExtensionWrapper {

    /**
     * The namespace of the generated R and BuildConfig classes. Also, the namespace used to resolve any relative class names that are
     * declared in the AndroidManifest.xml.
     */
    public var namespace: String?

    /**
     * Specifies the API level to compile your project against. The Android plugin requires you to configure this property.
     *
     * This means your code can use only the Android APIs included in that API level and lower. You can configure the compile sdk version by
     * adding the following to the `android` block: `compileSdk = 26`.
     *
     * You should generally
     * [use the most up-to-date API level](https://developer.android.com/guide/topics/manifest/uses-sdk-element.html#ApiLevels) available. If
     * you are planning to also support older API levels, it's good practice to
     * [use the Lint tool](https://developer.android.com/studio/write/lint.html) to check if you are using APIs that are not available in
     * earlier API levels.
     *
     * The value you assign to this property is parsed and stored in a normalized form, so reading it back may return a slightly different
     * value.
     *
     * This can be set on all Gradle projects with [com.android.build.api.dsl.SettingsExtension.compileSdk]
     */
    public var compileSdk: Int?

    /**
     * Specifies the SDK Extension level to compile your project against. This value is optional.
     *
     * When not provided the base extension for the given `compileSdk` API level will be selected.
     *
     * This can be set on all Gradle projects with [com.android.build.api.dsl.SettingsExtension.compileSdkExtension]
     */
    public var compileSdkExtension: Int?

    /**
     * Specify a preview API to compile your project against.
     *
     * For example, to try out the Android S preview, rather than `compileSdk = 30` you can use `compileSdkPreview = "S"`
     *
     * Once the preview APIs are finalized, they will be allocated a stable integer value.
     *
     * This can be set on all Gradle projects with [com.android.build.api.dsl.SettingsExtension.compileSdkPreview]
     */
    public var compileSdkPreview: String?

    /** Specify a minor API version for the compile SDK. This should be used with the compileSdk property to specify a full SDK version. */
    public var compileSdkMinor: Int?

    /** Configures all aspects regarding compile Sdk version, see [CompileSdkSpec] for more details. */
    public fun compileSdk(action: CompileSdkSpec.() -> Unit)

    /**
     * Specifies defaults for variant properties that the Android plugin applies to all build variants.
     *
     * You can override any `defaultConfig` property when
     * [configuring product flavors](https://developer.android.com/studio/build/build-variants.html#product-flavors)
     *
     * For more information about the properties you can configure in this block, see [DefaultConfig].
     */
    public val defaultConfig: DefaultConfig

    /**
     * Specifies Java compiler options, such as the language level of the Java source code and generated bytecode.
     *
     * For more information about the properties you can configure in this block, see [CompileOptions].
     */
    public val compileOptions: CompileOptions
}
