# Project type
type = "androidApplication"

applicationId = "com.frybits.starrynight.android"
namespace = "com.frybits.starrynight.android.app"

targetSdk = 37

enableMetro = true

[buildConfigs]

# Libraries to be used (maven address or version catalog name)
[dependencies]

# Used to add libraries into the "implementation" configuration
implementation = [
    { type = "library", name = "androidx.navigation3.runtime" },
    { type = "library", name = "metrox.android" },
    { type = "library", name = "metrox.viewmodel" },
    { type = "library", name = "tink.android" },

    # Api modules
    { type = "project", name = ":atproto:api" },
    { type = "project", name = ":auth:api" },
    { type = "project", name = ":home:api" },
    { type = "project", name = ":login:api" },
    { type = "project", name = ":navigation:api" },
    { type = "project", name = ":network:api" },
    { type = "project", name = ":utils:core:api" },

    # Data modules
    { type = "project", name = ":atproto:data" },

    # Main impl module
    { type = "project", name = ":starrynight:impl" },

    # Impl modules
    { type = "project", name = ":atproto:impl" },
    { type = "project", name = ":auth:impl" },
    { type = "project", name = ":home:impl" },
    { type = "project", name = ":login:impl" },
    { type = "project", name = ":network:impl" },
    { type = "project", name = ":persistence:impl" },
    { type = "project", name = ":utils:core:impl" },

    # UI
    { type = "project", name = ":starrynight:theme" },
]
