# Project type
type = "androidLibrary"

enableMetro = true
enableRoom = true

# Libraries to be used (maven address or version catalog name)
[dependencies]

implementation = [
    { type = "library", name = "androidx.datastore.preferences.android" },
    { type = "library", name = "androidx.collection" },
    { type = "library", name = "androidx.sqlite" },
    { type = "library", name = "kotlinx.coroutines.core" },
    { type = "library", name = "room.common" }
]

api = [
    { type = "project", name = ":atproto:data" },
    { type = "library", name = "androidx.datastore.preferences.core" },
    { type = "library", name = "androidx.datastore.core" },
    { type = "library", name = "room.runtime" },
]

ksp = [
    { type = "library", name = "room.ksp" },
]
