# Project type
type = "androidLibrary"

enableMetro = true
enableRoom = true

# Libraries to be used (maven address or version catalog name)
[dependencies]

implementation = [
    { type = "project", name = ":persistence:api" },
    { type = "project", name = ":auth:data" },
    { type = "library", name = "room.runtime" }
]

ksp = [
    { type = "library", name = "room.ksp" },
]
