# Project type
type = "androidLibrary"

enableMetro = true
enableWire = true

# Libraries to be used (maven address or version catalog name)
[dependencies]

implementation = [
    { type = "project", name = ":atproto:api" },
    { type = "project", name = ":auth:api" },
    { type = "project", name = ":auth:data" },
    { type = "project", name = ":network:api" },
    { type = "library", name = "kotlinx.serialization" },
    { type = "library", name = "kotlinx.serialization.json" },
    { type = "library", name = "retrofit" },
    { type = "library", name = "androidx.core" },
    { type = "library", name = "androidx.datastore" },
    { type = "library", name = "androidx.datastore.tink" },
]
