# Project type
type = "atprotoLibrary"

# Lexicons to download and compile
lexicons = [
    "app.bsky.actor.getProfiles",
    "app.bsky.actor.getProfile"
]

# Libraries to be used (maven address or version catalog name)
[dependencies]

# Used to add libraries into the "implementation" configuration
implementation = [
    { type = "library", name = "kotlinx.serialization" },
    { type = "library", name = "kotlinx.serialization.json" },
]
