# Project type
type = "javaLibrary"

# Libraries to be used (maven address or version catalog name)
[dependencies]
compileOnly = [
    { type = "library", name = "androidx.navigation3.runtime.desktop" },
]
